development:
  adapter: postgresql
  database: coffee_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: coffee_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: coffee_production
  pool: 5
  timeout: 5000
