# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f73e8d7ececf4c6075fa3d1616b11f4261a2fd2e17509ca033fbfe3be498e3dd33431123873851538bce2b0c6c7da4a4d07737921c346de6bc0d35849e49ad35

test:
  secret_key_base: 6590fd783cdad8da0bfe4faab030a36585dc3f117950da87e8fe201db1da4cc290353006b51591a5c2679a5470b78550a2640a0d458814048ead62c57fde6609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
